env:
  node: true
  es6: true
  jest: true
  browser: true
settings:
  import/resolver: node
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended

plugins:
  - import
  - jsx-a11y
  - prettier
  - react
  - react-hooks
rules:
  prettier/prettier: error
  no-console: warn
  no-underscore-dangle: 'off'
  no-param-reassign: warn
  no-nested-ternary: warn
  react/display-name: 'off'
  react/jsx-filename-extension: 'off'
  react/prop-types: 'off'
  react/jsx-curly-newline: 'off'
  react/jsx-one-expression-per-line: 'off'
  react/no-array-index-key: 'off'
  react/jsx-wrap-multilines: 'off'
  react/jsx-indent: 'off'
  react/jsx-props-no-spreading: warn
  react/destructuring-assignment: 'off'
  jsx-a11y/anchor-is-valid: 'off'
  jsx-a11y/click-events-have-key-events: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
  import/extensions:
    - error
    - ignorePackages
  import/no-unresolved:
    - error
    # Because of https://github.com/import-js/eslint-plugin-import/issues/1868
    - ignore:
        - "^@lowdefy\/.*$"
parserOptions:
  sourceType: module
  ecmaVersion: latest
